name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run_automation_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Build Docker Image
      run: |
        docker build -t my-appium-image .

    - name: Run Docker Container
      run: |
        docker run --privileged -d -p 6080:6080 -p 4723:4723 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name my-appium-container my-appium-image

    - name: Install APK on Emulator
      run: |
        docker exec -it my-appium-container adb install /app/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk

    - name: Run Maven Tests
      run: |
        docker exec -it my-appium-container mvn test

    - name: Stop Docker Container
      run: |
        docker stop my-appium-container

    - name: Archive test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: reports/

    - name: Publish test results as a GitHub Pages site
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAGES_TOKEN }}
        external_repository: ${{ github.repository }}
        publish_dir: ./reports/
        publish_branch: gh-pages 
        commit_message: "Publish Connexi Report"