name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run_automation_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Node.js (for Appium)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Appium
      run: |
        npm install -g appium
        appium --version

        - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk wget unzip
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O android-commandlinetools.zip
        unzip android-commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        mkdir -p $HOME/.android && echo "###" > $HOME/.android/repositories.cfg
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" \
          "platforms;android-30" \
          "system-images;android-30;google_apis;x86_64" \
          "emulator"

    - name: Set up Android Environment Variables
      run: |
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        echo "$HOME/android-sdk/emulator" >> $GITHUB_PATH

    - name: Create and Start Android Emulator
      run: |
        $HOME/android-sdk/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel"
        $HOME/android-sdk/emulator/emulator -avd test -no-window -no-audio -no-snapshot -gpu off &

    - name: Wait for Emulator to Boot
      run: |
        adb wait-for-device
        adb shell input keyevent 82

    - name: Install WebDriver Manager
      run: |
        python -c "from webdriver_manager.microsoft import EdgeChromiumDriverManager; EdgeChromiumDriverManager().install()"

    - name: Start Appium Server
      run: |
        appium --log-level error &

    - name: Run Robot Framework tests
      shell: bash
      run: |
        robot -d reports \
        -v BASE_URL:${{ secrets.BASE_URL }} \
        -v TABLEAU_URL:${{ secrets.TABLEAU_URL }} \
        -v ANALYTICS_EMAIL:${{ secrets.ANALYTICS_EMAIL }} \
        -v FORECASTING_EMAIL:${{ secrets.FORECASTING_EMAIL }} \
        -v INVENTORY_EMAIL:${{ secrets.INVENTORY_EMAIL }} \
        -v ORDERING_EMAIL:${{ secrets.ORDERING_EMAIL }} \
        -v PROCUREMENTSP_EMAIL:${{ secrets.PROCUREMENTSP_EMAIL }} \
        -v PROCUREMENT_EMAIL:${{ secrets.PROCUREMENT_EMAIL }} \
        -v QUALITYMANAGEMENT_EMAIL:${{ secrets.QUALITYMANAGEMENT_EMAIL }} \
        -v SUPPLYPLAN_EMAIL:${{ secrets.SUPPLYPLAN_EMAIL }} \
        -v VENDOR_EMAIL:${{ secrets.VENDOR_EMAIL }} \
        -i mobile \
        test-scenarios

    - name: Archive test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: reports/

    - name: Publish test results as a GitHub Pages site
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAGES_TOKEN }}
        external_repository: ${{ github.repository }}
        publish_dir: ./reports/
        publish_branch: gh-pages 
        commit_message: "Publish Connexi Report"
