name: Initialize Environment

on:
  workflow_dispatch: # Manual trigger
  push: # Optional: Trigger when changes are pushed to the repository

jobs:
  setup:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Webdriver Manager
      run: |
        python -c "from webdriver_manager.microsoft import IEDriverManager; IEDriverManager().install()"
