name: Publish Test Report

on:
  workflow_run:
    workflows: ["Run Tests"]  # Triggered by Run Tests workflow
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download test results artifact
      uses: actions/download-artifact@v4
      with:
        name: test-results
        path: ./reports

    - name: Publish test results as a GitHub Pages site
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAGES_TOKEN }}
        external_repository: ${{ github.repository }}
        publish_dir: ./reports/
        publish_branch: gh-pages
        commit_message: "Publish Kadena Test Results"